ports:
  - port: 5000
    onOpen: open-preview

tasks:
  - before: |
      export FLASK_APP=app
      export FLASK_ENV=development
    init: |
      source env/bin/activate
      python3 -m pip install flask
      pip install -e .
    command: |
      flask run
vscode:
  extensions:
    - ms-python.python